authentification/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = "authentification"

urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),

]

exam/urls.py
from django.conf.urls import url

from . import views

app_name = "exam"

urlpatterns = [
    url(r'^index/$', views.home, name='index'),

    url(r'^create_exam/$', views.create_exam, name='create_exam'),

    url(r'^active_exams/$', views.active_exams, name='active_exams'),

    url(r'^(?P<pk>[0-9]+)/create_question/$', views.create_question, name='create_question'),

    # url(r'¨message/$', views.message, name='create_exam'),

    url(r'^(?P<exam_id>[0-9]+)/question_list/$', views.affich_question, name='question_list'),

    url(r'^(?P<question_id>[0-9]+)/delete_question/$', views.delete_question, name='delete'),

    url(r'^(?P<question_id>[0-9]+)/edit_ONE/$', views.edit_ONE, name='edit_ONE'),

    url(r'^(?P<question_id>[0-9]+)/edit_FREE/$', views.edit_FREE, name='edit_FREE'),

    url(r'^(?P<question_id>[0-9]+)/edit_MULTI/$', views.edit_MULTI, name='edit_MULTI'),

    # url(r'^(?P<exam_id>[0-9]+)/try_exam/$', views.try_exam, name='affich'),
    #
    # url(r'^(?P<exam_id>[0-9]+)/try_exam/(?P<question_id>[0-9]+)$', views.dbsave, name='try'),

    url(r'^(?P<exam_id>[0-9]+)/score/$', views.score, name='score'),

    url(r'^(?P<exam_id>[0-9]+)/try_exam/$', views.preparation, name='preparation'),

    url(r'^(?P<exam_id>[0-9]+)/try_exam/(?P<indice>[0-9]+)$', views.pass_exam, name='try'),

    url(r'^(?P<exam_id>[0-9]+)/save_respone/(?P<indice>[0-9]+)/$', views.save_response, name='save-reponse'),

    # url(r'^(?P<exam_id>[0-9]+)/save_respone/(?P<indice>[0-9]+)$', views.score, name='save-reponse'),

    url(r'^addlocal_stu/$', views.addlocal_stu, name='local_students'),

    url(r'^send/$', views.addstranger_stu, name='invitation'),

    url(r'^MYstudents/$', views.assignTO_exam, name='MYstudents'),

    url(r'^indexUSER/$', views.homeUSER, name='indexUSER'),

    url(r'^(?P<exam_id>[0-9]+)/try_examSTUD/$', views.preparationSTUD, name='preparationSTUD'),

    url(r'^(?P<exam_id>[0-9]+)/try_examSTUD/(?P<indice>[0-9]+)$', views.pass_examSTUD, name='trySTUD'),

    url(r'^(?P<exam_id>[0-9]+)/save_responeSTUD/(?P<indice>[0-9]+)/$', views.save_responseSTUD,
        name='save-reponseSTUD'),

    url(r'^(?P<exam_id>[0-9]+)/score_user/$', views.certif, name='scoreUSER'),

    url(r'^(?P<exam_id>[0-9]+)/certif/$', views.certif, name='certif'),

    url(r'^(?P<exam_id>[0-9]+)/correction/$', views.correction, name='correction'),

    # url(r'^STUD_EXAMS/$', views.user_exams, name='STUD_EXAMS'),

    # url(r'^becomePROF/$', views.becomePROF, name='becomePROF'),

]

quiz/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
# my_project/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [

                  path('admin/', admin.site.urls),
                  path('authentification/', include('authentification.urls')),
                  path('exam/', include('exam.urls')),
                  url(r'^admin/', admin.site.urls),
              ] + static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

exam/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Exam(models.Model):
    name = models.CharField(max_length=100)
    # logo = models.ImageField(upload_to="media/logs/")
    logo = models.ImageField(upload_to='logs', blank=True, null=True)
    description = models.TextField(max_length=500)
    timer = models.IntegerField(default=0)
    is_active = models.BooleanField(default=False)
    category = models.CharField(max_length=30, default='')
    mode = models.CharField(max_length=20, default='')
    success_score = models.IntegerField(default=70)
    prof = models.ForeignKey(User, on_delete=models.CASCADE, related_name='prof', null=True, blank=True)


    def ___str__(self):
        return self.name


class Question(models.Model):
    ex = models.ForeignKey(Exam, on_delete=models.CASCADE, null=True)
    description = models.TextField(max_length=500)
    point = models.CharField(max_length=4)
    header_text = models.TextField(max_length=70)
    footer_text = models.TextField(max_length=70)
    success_message = models.CharField(max_length=30)
    fail_message = models.CharField(max_length=30)
    correct_answer = models.CharField(max_length=200, default='')

    def __str__(self):
        return self.description


class One_answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, null=True)
    answer_variant = models.TextField(max_length=200)
    answer_description = models.TextField(max_length=200)
    point = models.IntegerField(default=0)
    # is_rightONE = models.BooleanField(default=False)



class Free_Text(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, null=True)
    text = models.TextField(max_length=500)


class Multichoice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, null=True)
    multi_variant = models.TextField(max_length=200)
    multi_descp = models.TextField(max_length=200)
    point = models.IntegerField(default=0)


class Answer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE, related_name='Exam', default=1)
    One_answer = models.ForeignKey(One_answer, on_delete=models.CASCADE, blank=True, null=True)
    multi_choice_answer = models.ForeignKey(Multichoice, on_delete=models.CASCADE, blank=True, null=True)
    free_text = models.CharField(max_length=1000, default='', blank=True, null=True)
    score_question = models.IntegerField(default=0)


class Groupst(models.Model):
    professor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='professor', null=True, blank=True)
    student = models.ForeignKey(User, on_delete=models.CASCADE, related_name='student', blank=True, null=True)
    assigned_exam = models.ForeignKey(Exam, on_delete=models.CASCADE, related_name='assigned_exam', blank=True,
                                      null=True)

exam/forms.py
from django import forms
from django.forms import ModelForm
from .models import Exam, Question


class Create_examForm(forms.ModelForm):
    class Meta:
        model = Exam
        fields = {'name', 'description', 'timer', 'is_active', 'category', }

#
# class Create_questionForm(forms.ModelForm):
#     class Meta:
#         model = Question
#         fields = {'description', 'point', 'header_text', 'footer_text', 'success_message', 'fail_message'}

exam/views.py
# from django.template import loader
from random import *

from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect

from .models import Exam, Free_Text, Question, One_answer, Multichoice, Answer, Groupst


def home(request):
    return render(request, 'exam/index.html')


def message(request):
    return render(request, 'exam/message.html')


# créer les examens
def create_exam(request):
    if request.method == 'POST':
        examName = request.POST['examName']
        ExamDesc = request.POST['ExamDesc']
        category = request.POST['category']
        logo = request.FILES['logo']
        mode1 = request.POST['mode']
        score = request.POST['success_score']
        timer1 = request.POST['timer']

        exam = Exam()
        exam.name = examName
        exam.description = ExamDesc
        exam.category = category
        exam.logo = logo
        exam.mode = mode1
        exam.success_score = score
        exam.timer = timer1
        exam.prof = request.user

        exam.save()
        return render(request, 'exam/create_exam.html')
    else:
        return render(request, 'exam/create_exam.html')


# afficher la liste des examens
def active_exams(request):
    exams = Exam.objects.filter(prof=request.user)
    exams = Exam.objects.filter(prof=request.user)
    context = {'exams': exams}
    return render(request, 'exam/active_exams.html', context)


# créer les différents types des questions

def create_question(request, pk):
    if request.method == 'POST':
        qdes = request.POST['qdes']
        qpoint = request.POST['qpoint']
        qht = request.POST['qht']
        qft = request.POST['qft']
        success_msg = request.POST['success_msg']
        fail_msg = request.POST['fail_msg']
        type = request.POST['type']
        correct = request.POST['correct_answer']

        question = Question()

        question.ex = Exam.objects.get(pk=pk)
        question.description = qdes
        question.point = qpoint
        question.header_text = qht
        question.footer_text = qft
        question.success_message = success_msg
        question.fail_message = fail_msg
        question.correct__answer = correct
        question.save()

        if type == "one_answer":
            choice1 = One_answer()
            choice2 = One_answer()
            choice3 = One_answer()

            choice1.question = question
            choice1.answer_variant = request.POST['answ_variant1']
            choice1.answer_description = request.POST['answ_desc1']
            choice1.point = request.POST['point1']
            choice1.save()
            choice2.question = question
            choice2.answer_variant = request.POST['answ_variant2']
            choice2.answer_description = request.POST['answ_desc2']
            choice2.point = request.POST['point2']
            choice2.save()
            choice3.question = question
            choice3.answer_variant = request.POST['answ_variant3']
            choice3.answer_description = request.POST['answ_desc3']
            choice3.point = request.POST['point3']
            choice3.save()

        elif type == "free_text":
            text = request.POST['text']

            choice = Free_Text()

            choice.question = question
            choice.text = text
            choice.save()

        else:
            choice1 = Multichoice()
            choice2 = Multichoice()
            choice3 = Multichoice()

            choice1.question = question
            choice1.multi_variant = request.POST['answer_variant1']
            choice1.multi_descp = request.POST['multidescp1']
            choice1.point = request.POST['pointn1']
            choice1.save()

            choice2.question = question
            choice2.multi_variant = request.POST['answer_variant2']
            choice2.multi_descp = request.POST['multidescp2']
            choice2.point = request.POST['pointn2']
            choice2.save()

            choice3.question = question
            choice3.multi_variant = request.POST['answer_variant3']
            choice3.multi_descp = request.POST['multidescp3']
            choice3.point = request.POST['pointn3']
            choice3.save()

        return render(request, 'exam/index.html')
    else:
        return render(request, 'exam/create_question.html')


# afficher la liste des questions pour ajouter les boutons edit et delete
def affich_question(request, exam_id):
    exam = Exam.objects.get(pk=exam_id)
    question = exam.question_set.all()
    context = {'exam': exam}
    # context = {'question': question}
    return render(request, 'exam/question_list.html', context)


# supprimer une question
def delete_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    question.delete()
    return render(request, 'exam/index.html')


# edit questions
def edit_ONE(request, question_id):
    question = Question.objects.get(pk=question_id)
    if request.method == 'POST':
        question.description = request.POST['desc']
        question.point = request.POST['point']
        question.header_text = request.POST['qht']
        question.footer_text = request.POST['qft']
        question.success_message = request.POST['success_msg']
        question.fail_message = request.POST['fail_msg']
        question.save()

        x = request.POST.get('id1', False)
        y = request.POST.get('id2', False)
        z = request.POST.get('id3', False)

        ans1 = get_object_or_404(One_answer, pk=x)
        ans2 = get_object_or_404(One_answer, pk=y)
        ans3 = get_object_or_404(One_answer, pk=z)
        ans1.answer_variant = request.POST.get('answer_variant1', False)
        ans1.answer_description = request.POST.get('answer_desc1', False)
        ans1.point = request.POST.get('point1', False)

        ans1.answer_variant = request.POST['answer_variant1']
        ans1.answer_description = request.POST['answer_description1']
        ans1.point = request.POST['point1']
        ans1.save()

        answ_variant2 = request.POST['answer_variant2']
        answ_desc2 = request.POST['answer_description2']
        point2 = request.POST['point2']
        ans2.answer_variant = answ_variant2
        ans2.answer_description = answ_desc2
        ans2.point = point2
        ans2.save()
        answ_variant3 = request.POST['answer_variant3']
        answ_desc3 = request.POST['answer_description3']
        point3 = request.POST['point3']
        ans3.answer_variant = answ_variant3
        ans3.answer_description = answ_desc3
        ans3.point = point3
        ans3.save()
        return render(request, 'exam/index.html')
    else:
        context = {'question': question}
        return render(request, 'exam/modif_ONE.html', context)


def edit_MULTI(request, question_id):
    question = Question.objects.get(pk=question_id)
    if request.method == 'POST':
        question.description = request.POST['desc']
        question.point = request.POST['point']
        question.header_text = request.POST['qht']
        question.footer_text = request.POST['qft']
        question.success_message = request.POST['success_msg']
        question.fail_message = request.POST['fail_msg']
        question.save()

        x = request.POST.get('id1', False)
        y = request.POST.get('id2', False)
        z = request.POST.get('id3', False)

        ans1 = get_object_or_404(Multichoice, pk=x)
        ans2 = get_object_or_404(Multichoice, pk=y)
        ans3 = get_object_or_404(Multichoice, pk=z)
        ans1.answer_variant = request.POST.get('answer_variant1', False)
        ans1.answer_description = request.POST.get('answer_desc1', False)
        ans1.point = request.POST.get('point1', False)

        ans1.answer_variant = request.POST['answer_variant1']
        ans1.answer_description = request.POST['answer_desc1']
        ans1.point = request.POST['point1']
        ans1.save()

        ans2.answer_variant = request.POST['answer_variant2']
        ans2.answer_description = request.POST['answer_desc2']
        ans2.point = request.POST['point2']
        ans2.save()

        ans3.answer_variant = request.POST['answer_variant3']
        ans3.answer_description = request.POST['answer_desc3']
        ans3.point = request.POST['point3']
        ans3.save()
        return render(request, 'exam/index.html')
    else:
        context = {'question': question}
        return render(request, 'exam/modif_MULTI.html', context)


def edit_FREE(request, question_id):
    question = Question.objects.get(pk=question_id)
    if request.method == 'POST':
        question.description = request.POST['description']
        question.point = request.POST['point']
        question.header_text = request.POST['qht']
        question.footer_text = request.POST['qft']
        question.success_message = request.POST['success_msg']
        question.fail_message = request.POST['fail_msg']
        question.save()
        x = request.POST['id']
        t = Free_Text.objects.get(pk=x)
        t.text = request.POST['text']
        t.save()
        return render(request, 'exam/index.html')
    else:
        context = {'question': question}
        return render(request, 'exam/modif_FREE.html', context)


# try_exam


listevide = []


def preparation(request, exam_id):
    global listevide
    exam = Exam.objects.get(pk=exam_id)
    L1 = Question.objects.filter(ex=exam).values_list('id', flat=True)
    # stockage de chq liste dans la session de user
    request.session['question_ids'] = sample(list(L1), len(L1))  # aleatoire

    return render(request, 'exam/start_exam.html', {'exam': exam})


# sera appelée dans save_response to pass from question to another
def pass_exam(request, exam_id, indice):
    global listevide
    question_ids = request.session.get('question_ids')
    indice = int(indice) if not isinstance(indice, int) else indice
    id = question_ids[indice]

exam/templates/exam/MYstudents.html
{% extends "exam/base.html" %}
{% block content %}

<table class="table">
    <thead>
    <tr>
        <th scope="col">First name</th>
        <th scope="col">Last name</th>
        <th scope="col">Email</th>
        <th scope="col">assign to</th>
    </thead>
    <tbody>
    {% for stu in grp %}
    <tr>
        <td>{{stu.student.first_name}}</td>
        <td>{{stu.student.last_name}}</td>
        <td>{{stu.student.email}}</td>

        <form method="post" action="">
            {% csrf_token %}
            <td><input type="hidden" value="{{ stu.student.email }}" name="emailst"></td>
            <td>
                <select name="drop" id="exams">
                    <option>select an exam</option>
                    {% for ex in exams %}
                    <option value="{{ex.id}}">{{ex.name}}</option>
                    {% endfor %}
                </select>
                <input type="submit" value="OK" class="btn btn-success btn-sm" name="submit">
            </td>
        </form>
    </tr>
    {% endfor %}

    </tbody>
</table>

{% endblock %}

exam/templates/exam/certificat.html
{% extends 'exam/base_user.html' %}
{% block content %}
<div style="width:800px; height:600px; padding:20px; text-align:center; border: 10px solid #787878">
    <div style="width:750px; height:550px; padding:20px; text-align:center; border: 5px solid #787878">
        <span style="font-size:50px; font-weight:bold">Certificate of Completion</span>
        <br><br>
        <span style="font-size:25px"><i>This is to certify that</i></span>
        <br><br>
        <span style="font-size:30px"><b> {{student}}</b></span><br/><br/>
        <span style="font-size:25px"><i>has completed the course</i></span> <br/><br/>
        <span style="font-size:30px">{{exam.name}}</span> <br/><br/>
        <span style="font-size:25px"><i>dated</i></span><br>
        {% now "jS \o\f F,Y" %}
        <span style="font-size:30px"></span>
    </div>
</div>

{% endblock %}

exam/templates/exam/message.html
{% extends 'exam/base.html' %}
{% block content %}
<em>exam created</em>
{%endblock%}

exam/templates/exam/modetraining2.html
{% extends "exam/base_user.html" %}
{% block content %}
<style>
body {font-family: Arial, Helvetica, sans-serif;}

/* The Modal (background) */
.modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1 1; /* Sit on top */
    padding-top: 70px; /* Location of the box */
    left: 0;
    top: 0;
    width: 50%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
}

/* Modal Content */
.modal-content {
    background-color: #fefefe;
    margin: auto;
    padding: 20px;
    border: 1px solid #888;
    width: 80%;
}

/* The Close Button */
.close {
    color: #aaaaaa;
    float: left;
    font-size: 28px;
    font-weight: bold;
}

.close:hover,
.close:focus {
    color: red;
    text-decoration: none;
    cursor: pointer;
}

</style>


<div class="container">
    <form method="post" action="{% url 'exam:save-reponseSTUD'  exam_id=q.ex.id indice=indice %}">
        {% csrf_token %}

        {%if q.multi_choice_answer_set.all %}
        {% include "exam/multichoiceQUESTION.html" with question=q %}
        {%endif%}

        {%if q.one_answer_set.all %}
        {% include "exam/one_answerQUESTION.html" with question=q %}
        {%endif%}
        {%if q.free_text_set.all %}
        {% include "exam/free_textQUESTION.html" with question=q %}
        {%endif%}

        <div>

            <input type="submit" value="submit" class="btn btn-warning" name="submit">
        </div>

    </form>


    <!-- display correct answer using modal box-->
    <button id="myBtn">correct answer</button>
    <div id="myModal" class="modal">
        <!-- Modal content -->
        <div class="modal-content">
            <span class="close">&times;</span>
            <p>the correct answer: </p>
            <p>{{q.correct_answer}}</p>
        </div>
    </div>

    <div class="col-lg-4">
        <div class="card">
            <div class="card-header">
                <strong>Questions</strong>
            </div>
            <div class="card-body">
                {% for i in question_ids %}
                {% if i in liste1 %}
                <a href="{% url 'exam:save-reponseSTUD'  exam_id=q.ex.id indice=forloop.counter0 %}"
                   class="btn  btn-success" style="margin:3px">{{forloop.counter}} </a>
                {% else %}
                <a href="{% url 'exam:save-reponseSTUD'  exam_id=q.ex.id indice=forloop.counter0 %}"
                   class="btn  btn-danger" style="margin:3px">{{forloop.counter}} </a>
                {% endif %}
                {% endfor %}


            </div>
        </div>
    </div>
    <div>
        <center><a href="{% url 'exam:scoreUSER' exam_id=exam_id %}" class="btn btn-block btn-info">finish </a>
        </center>
    </div>


</div>
<script>
// Get the modal
var modal = document.getElementById('myModal');

// Get the button that opens the modal
var btn = document.getElementById("myBtn");

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks the button, open the modal
btn.onclick = function() {
    modal.style.display = "block";
}

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
    modal.style.display = "none";
}

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}



</script>
{% endblock %}

exam/templates/exam/modif_FREE.html
  {% extends 'exam/base.html' %}

{% block content %}
<div class="container">
    <form method="post">
        <div class="col-xs-12 col-sm-12">
            {%csrf_token%}
            <div class="card">
                <div class="card-header">
                    <div class="col-lg-6 ">
                        <strong>Edit free_text-question</strong></div>
                </div>
                <div class="card-body card-block">
                    <div class="form-group">
                        <label class=" form-control-label">Description</label>
                        <div class="input-group">
                            <div class="input-group-addon"></div>
                            <input class="form-control" value="{{question.description}}" name="description">
                        </div>

                    </div>
                    <div class="form-group">
                        <label class=" form-control-label">point</label>
                        <div class="input-group">
                            <div class="input-group-addon"><i class="fa fa-usd"></i></div>
                            <input class="form-control" type="number" value="{{question.point}}" name="point">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class=" form-control-label">Header text</label>
                        <div class="input-group">
                            <div class="input-group-addon"><i class="fa fa-phone"></i></div>
                            <input class="form-control" value="{{question.header_text}}" name="qht">
                        </div>

                    </div>
                    <div class="form-group">
                        <label class=" form-control-label">footer text</label>
                        <div class="input-group">
                            <input class="form-control" value="{{question.footer_text}}" name="qft">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class=" form-control-label">success msg</label>
                        <div class="input-group">
                            <input class="form-control" value="{{question.success_message}}" name="success_msg">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class=" form-control-label">fail msg</label>
                        <div class="input-group">
                            <div class="input-group-addon"><i class="fa fa-usd"></i></div>
                            <input class="form-control" value="{{question.fail_message}}" name="fail_msg">
                        </div>
                    </div>
                </div>

         <div class="card-body">
      <label class=" form-control-label">free text</label>
                 {%for choix in question.free_text_set.all %}
             <input type="hidden" value="{{choix.id}}" name="id">
             <textarea class="form-control" placeholder="The Text ..." name="text">{{choix.text}}</textarea>
                               {%endfor%} </div>


          </div>
        <div class="form-group row">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-info">save</button>

            </div>
        </div>
   </div>

</form>
    {% endblock %} </div>

exam/templates/exam/non_certifiedEXAM.html
{% extends 'exam/base_user.html' %}
{% block content %}

<!--Display the countdown timer in an element-->
<p id="demo">TIMER</p>
<div id="time">
    <script>
// Set the date we're counting down to
var countDownDate = new Date("Aug 31, 2018 20:45:00").getTime();

// Update the count down every 1 second
var x = setInterval(function() {

// Get todays date and time
var now = new Date().getTime();

// Find the distance between now and the count down date
var distance = countDownDate - now;

// Time calculations for days, hours, minutes and seconds
<!--var days = Math.floor(distance / (1000 * 60 * 60 * 24));-->
var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
var seconds = Math.floor((distance % (1000 * 60)) / 1000);

// Display the result in the element with id="demo"
document.getElementById("demo").innerHTML = hours + "h "
+ minutes + "m " + seconds + "s ";

// If the count down is finished, write some text
if (distance < 0) {
clearInterval(x);
document.getElementById("demo").innerHTML = "time_over";
window.location.href = 'index'

}
}, 1000);

    </script>
</div>


<div class="container">
    <form method="post" action="{% url 'exam:save-reponseSTUD'  exam_id=q.ex.id indice=indice %}">
        {% csrf_token %}

        {%if q.multi_choice_answer_set.all %}
        {% include "exam/multichoiceQUESTION.html" with question=q %}
        {%endif%}
        {%if q.one_answer_set.all %}
        {% include "exam/one_answerQUESTION.html" with question=q %}
        {%endif%}
        {%if q.free_text_set.all %}
        {% include "exam/free_textQUESTION.html" with question=q %}
        {%endif%}
        <div>

            <input type="submit" value="submit" class="btn btn-warning" name="submit">
        </div>

        <div class="col-lg-4">
            <div class="card">
                <div class="card-header">
                    <strong>Questions</strong>
                </div>
                <div class="card-body">
                    {% for i in question_ids %}
                    {% if i in liste3 %}

                    <a href="{% url 'exam:save-reponseSTUD'  exam_id=q.ex.id indice=forloop.counter0 %}"
                       class="btn  btn-success" style="margin:3px">{{forloop.counter}} </a>
                    {% else %}

                    <a href="{% url 'exam:save-reponseSTUD'  exam_id=q.ex.id indice=forloop.counter0 %}"
                       class="btn  btn-danger" style="margin:3px">{{forloop.counter}} </a>
                    {% endif %}
                    {%endfor%}

                </div>
            </div>
            <div>
                <center><a href="{% url 'exam:scoreUSER' exam_id=exam_id %}" class="btn btn-block btn-info">finish </a>
                </center>
            </div>


    </form>
</div>

{% endblock %}

exam/templates/exam/one_answerQUESTION.html
<div class="col col-md-3"><label class=" form-control-label">{{q.description}}</label></div>
<div class="col col-md-9">
    <div class="form-check">
        {%for choix in question.one_answer_set.all %}
        <div class="radio">
            <input type="radio" id="{{choix.id}}" name="radios" value="{{choix.id}}" class="form-check-input">{{choix.answer_variant}}
        </div>

        {%endfor%}

    </div>
</div>

exam/templates/exam/question_list.html
{% extends 'exam/base.html' %}
    {% block content %}
        <div class="container">
         {% for q in exam.question_set.all %}
            {%if q.one_answer_set.all %}
         <div class="card"  >

             <div class="card-header">
                 <div class="col-lg-6 ">
                     <strong class="card-title">{{q.description}}</strong></div>
                   <div class="col-lg-3 ">
                       <a href="/exam/{{q.id}}/edit_ONE" class="btn btn-success btn-block">edit</a>
                                           </div>
                    <div class="col-lg-3">
                        <a href="/exam/{{q.id}}/delete_question" class="btn btn-warning btn-block">delete</a>
                                     </div>

             </div>

             </div>

             {% endif %}
              {% if q.free_text_set.all %}
               <div class="card"  >
                  <div class="card-header">
                 <div class="col-lg-6 ">
                     <strong class="card-title">{{q.description}}</strong></div>
                   <div class="col-lg-3 ">
                       <a href="/exam/{{q.id}}/edit_FREE" class="btn btn-success btn-block">edit</a>
                                           </div>
                    <div class="col-lg-3">
                                         <a href="/exam/{{q.id}}/delete_question" class="btn btn-warning btn-block">delete</a>
                                     </div>
                  </div>
               </div>
               {% endif %}
              {% if q.multichoice_set.all %}
             <div class="card"  >
                      <div class="card-header">
                 <div class="col-lg-6 ">
                     <strong class="card-title">{{q.description}}</strong></div>
                   <div class="col-lg-3 ">
                       <a href="/exam/{{q.id}}/edit_MULTI" class="btn btn-success btn-block">edit</a>
                                           </div>
                    <div class="col-lg-3">
                                         <a href="/exam/{{q.id}}/delete_question" class="btn btn-warning btn-block">delete</a>
                                     </div>
                      </div>
             </div>
               {% endif %}

         {% endfor %}
        </div>
            {% endblock %}